language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.3
  - 8.0
  - nightly

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  fast_finish: true
  include:
    - php: 5.6
      env: COMPOSER_FLAGS="--prefer-lowest"
    - php: 5.6
      env: SYMFONY_VERSION=2.7.*
    - php: 5.6
      env: SYMFONY_VERSION=2.8.*
    - php: 5.6
      env: SYMFONY_VERSION="3.3.*"
    - php: 5.6
      env: SYMFONY_VERSION="3.4.*"
    - php: 7.1
      env: SYMFONY_VERSION="4.0.*"
    - php: 7.3
      env: SYMFONY_VERSION="4.2.*"
    - php: 8.0
      env: SYMFONY_VERSION="5.4.*"
    - php: 8.0
      env: SYMFONY_VERSION="6.0.*"
  allow_failures:
    - php: nightly

before_script:
  - composer selfupdate
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require "symfony/symfony:${SYMFONY_VERSION}" --no-update; fi;
  - composer update --prefer-dist --no-interaction $COMPOSER_FLAGS
